"""
    This file was generated by TONDev.
    TONDev is a part of TON OS (see http://ton.dev).
"""
from tonos_ts4 import ts4
from tonos_ts4.address import Address


def testRootDeploy():
    # Place your code of the test here
    assert eq(deploymentFee,
              rootDeployerContract.call_getter('deploymentFee'))
    print('Root deploy ok')


def testCollectionDeploy():
    clientKeyPair = ts4.make_keypair()
    multisigWallet = ts4.BaseContract('multisig/SafeMultisigWallet', dict(
        owners=[clientKeyPair[1]], reqConfirms=0))
    # multisigWallet.call_method()
    print('Collection deploy ok')


if __name__ == '__main__':
    # Initialize TS4 by specifying where the artifacts of the used contracts are located
    # verbose: toggle to print additional execution info
    ts4.init('../contracts/', verbose=True)
    eq = ts4.eq

    rootKeyPair = ts4.make_keypair()
    deploymentFee = 500_000_000
    deploymentFeePart = deploymentFee / 2
    collectionRootCode = ts4.load_code_cell('CollectionRoot')
    rootDeployerContract = ts4.BaseContract(
        'RootDeployer', dict(_pubkey=rootKeyPair[1], _collectionRootCode=collectionRootCode, _deploymentFee=deploymentFee), keypair=rootKeyPair)

    testRootDeploy()
    testCollectionDeploy()
