export const MARKETPLACE = {
  collectionDeploymentFee: 2.4,
  fee: process.env.NEXT_PUBLIC_MARKETPLACE_FEE ? +process.env.NEXT_PUBLIC_MARKETPLACE_FEE : 3,
  changeManagerFee: process.env.NEXT_PUBLIC_CHANGE_MANAGER_FEE ? +process.env.NEXT_PUBLIC_CHANGE_MANAGER_FEE : 2.1,
  offerCreationFee: process.env.NEXT_PUBLIC_OFFER_CREATION_FEE ? +process.env.NEXT_PUBLIC_OFFER_CREATION_FEE : 2,
  tip3ServiceFee: process.env.NEXT_PUBLIC_OFFER_CREATION_FEE ? +process.env.NEXT_PUBLIC_OFFER_CREATION_FEE : 4.61,
  cancelOfferFee: process.env.NEXT_PUBLIC_CANCEL_OFFER_FEE ? +process.env.NEXT_PUBLIC_CANCEL_OFFER_FEE : 0.1,
  transferFee: process.env.NEXT_PUBLIC_TRANSFER_FEE ? +process.env.NEXT_PUBLIC_TRANSFER_FEE : 1.1,
  nextBidRatio: 1.1,
  mintingFeeTip4: 1.4,
  saleFeeTip4: 2.1,
  mintingFeeMultiple: 3,
  saleFeeMultiple: 2,
  mintingFeeBulk: 3,
  putOnSaleBulk: 2,
  mintingFee: 2,
  deployCollectionFee: 2.4,
  offerMaxPrice: 999999999,
  offerMinPrice: 1,
};
